import { QcCriterion, QcCriterionResult, QcProgramConfiguration, QcPolicyConfiguration } from "@avidity/shared";
export interface Named { id: string; name: string; }
export interface Person { id: string; firstName: string; lastName: string; }
export interface Rubric extends Named { kind: string; revision: number; criteria: QcCriterion[]; passThreshold: number; reinspectionCount: number; publishedAt: string | null; }
export interface Policy extends Named { revision: number; clientId: string; projectId: string | null; categoryId: string | null; agreementType: string; effectiveFrom: string; effectiveUntil: string | null; publishedAt: string | null; configuration: QcPolicyConfiguration; }
export interface Lookups { reviewers?: Person[]; currentUserId: string; permissions: string[]; users: Person[]; clients: Named[]; projects: Array<Named & { clientId: string | null }>; categories: Named[]; rubrics: Rubric[]; }
export interface Program { lastProcessingAt?: string | null; processingErrorCode?: string | null; version: number; captureEnabled: boolean; processingEnabled: boolean; deliveryEnabled: boolean; startedAt: string | null; configuration: QcProgramConfiguration; readiness: string[]; }
export interface SettingsData extends Lookups { program: Program; policies: Policy[]; statuses: Array<Named & { category: string }>; mailboxes: Array<Named & { provider: string; outboundMode: string }>; agreementTypes: Named[]; }
export interface Finding { id: string; code: string; severity: string; evidence: Record<string, unknown>; overriddenAt: string | null; overrideReason: string | null; }
export interface History { id: string; action: string; createdAt: string; actor?: Person; metadata: Record<string, unknown>; }
export interface Review { billingState: string; billingReleasedAt: string | null; billingReleaseReason: string | null; id: string; ticketId: string | null; deliverableId: string | null; status: string; version: number; ownerId: string | null; reviewerId: string | null; owner: Person | null; reviewer: Person | null; ticket: { id: string; ticketNumber: string; subject: string; client: Named | null } | null; deliverable: { id: string; name: string; project: Named & { clientId: string | null } } | null; findings: Finding[]; selectionReasons: string[]; score: number | null; finalizedAt: string | null; acknowledgedAt: string | null; createdAt: string; rubric: Rubric | null; policy: Policy | null; results: QcCriterionResult[] | null; actions?: Action[]; history?: History[]; }
export interface Action { review?: { ownerId: string | null; ticket: { ticketNumber: string } | null; deliverable: { name: string } | null }; id: string; reviewId: string; ownerId: string; owner?: Person; kind: string; title: string; note: string; dueAt: string | null; status: string; version: number; completionEvidence: string | null; }
export interface Page<T> { items: T[]; total: number; page: number; pageSize: number; }
export interface Metrics { historical: { cycles: number; firstResponseSample: number; averageFirstResponseElapsedMinutes: number | null; resolutionSample: number; averageResolutionElapsedMinutes: number | null; basis: string }; cycles: number; completeCycles: number; incompleteCycles: number; firstResponseSample: number; averageFirstResponseBusinessMinutes: number | null; resolutionSample: number; averageResolutionBusinessMinutes: number | null; evaluatedObligations: number; breachedObligations: number; slaCompliancePercent: number | null; }
export interface Overview { generatedAt: string; period: { cohort: string }; program: Pick<Program, "captureEnabled" | "processingEnabled" | "startedAt" | "readiness" | "lastProcessingAt" | "processingErrorCode">; pendingSourceEvents: number | null; service: Metrics; technicians?: Array<Metrics & { ownerId: string; inspected: number; averageScore: number | null; passRatePercent: number | null }>; rework?: { reopenedCycles: number; reopenCyclePercent: number | null }; quality: { completedInPeriod?: number; failedInPeriod?: number; passRatePercent?: number | null; selected: number; scored: number; averageScore: number | null; passed: number; pending: number; flags: number; bulkCleared: number }; followUp: { reinspectionRemaining?: number; open: number; overdue: number; recognition: number }; creative: { originalCommitmentOnTime?: number; originalCommitmentSample?: number; total: number; delivered: number; onTime: number; overdue: number; averageRevisionRounds: number | null }; trends: Array<Metrics & { day: string }>; }
export const personName = (person?: Person | null) => person ? `${person.firstName} ${person.lastName}`.trim() : "Unassigned";
export const label = (text: string) => text.toLowerCase().replaceAll("_", " ").replace(/^./, char => char.toUpperCase());
export const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString() : "—";
export const metric = (value: number | null | undefined, suffix = "") => value === null || value === undefined ? "Not measurable" : `${value.toLocaleString()}${suffix}`;
