"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { apiFetch } from "@/lib/api";
import { Action, History, Lookups, Page, formatDate, label, localInputDate, personName } from "./qc.types";

export function QcActions({ lookups, initialOwner = "" }: { lookups: Lookups; initialOwner?: string }) {
  const [owner, setOwner] = useState(initialOwner); const [status, setStatus] = useState(""); const [kind, setKind] = useState("");
  const [search, setSearch] = useState(""); const [client, setClient] = useState(""); const [overdue, setOverdue] = useState(false); const [page, setPage] = useState(1);
  const [data, setData] = useState<Page<Action> | null>(null); const [error, setError] = useState("");
  const query = new URLSearchParams({ page: String(page), pageSize: "25", ...(owner ? { ownerId: owner } : {}), ...(status ? { status } : {}), ...(kind ? { kind } : {}), ...(client ? { clientId: client } : {}), ...(search ? { search } : {}), ...(overdue ? { overdue: "true" } : {}) }).toString();
  const reload = useCallback(async () => { setError(""); try { setData(await apiFetch<Page<Action>>(`/qc/action-page?${query}`)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Actions could not be loaded."); } }, [query]);
  useEffect(() => { void reload(); }, [reload]);
  return <div className="qc-stack"><div className="qc-inline"><h2>Coaching & actions</h2><button onClick={() => { setOwner(lookups.currentUserId); setStatus(""); setPage(1); }}>My actions</button><button onClick={() => { setStatus("COMPLETED"); setOverdue(false); setPage(1); }}>Awaiting verification</button></div>
    <div className="qc-filters" onChange={() => setPage(1)}><label>Search actions<input value={search} onChange={event => setSearch(event.target.value)} placeholder="Title or ticket number" /></label><label>Action owner<select value={owner} onChange={event => setOwner(event.target.value)}><option value="">All permitted owners</option>{lookups.users.map(user => <option key={user.id} value={user.id}>{personName(user)}</option>)}</select></label><label>Action status<select value={status} onChange={event => setStatus(event.target.value)}><option value="">All states</option>{["OPEN", "ACKNOWLEDGED", "COMPLETED", "VERIFIED"].map(value => <option key={value} value={value}>{label(value)}</option>)}</select></label><label>Action type<select value={kind} onChange={event => setKind(event.target.value)}><option value="">All types</option>{["COACHING", "CORRECTIVE", "RECOGNITION"].map(value => <option key={value} value={value}>{label(value)}</option>)}</select></label><label>Client<select value={client} onChange={event => setClient(event.target.value)}><option value="">All clients</option>{lookups.clients.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="qc-check"><input type="checkbox" checked={overdue} onChange={event => setOverdue(event.target.checked)} />Overdue only</label></div>
    {error && <p role="alert">{error}</p>}<p className="qc-muted">{data?.total ?? 0} matching actions. Completed work requires reviewer verification; verified follow-up does not automatically close its inspection.</p>
    {data?.items.map(item => <ActionCard key={`${item.id}:${item.version}`} item={item} lookups={lookups} reload={reload} />)}{data && !data.items.length && <p>No actions match these filters.</p>}
    <div className="qc-inline qc-pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} · {data?.total ?? 0} actions</span><button disabled={!data || page * data.pageSize >= data.total} onClick={() => setPage(page + 1)}>Next</button></div>
  </div>;
}
export function ActionCard({ item, lookups, reload }: { item: Action; lookups: Lookups; reload: () => Promise<void> }) {
  const [evidence, setEvidence] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState(false);
  const [history, setHistory] = useState<History[] | null>(null);
  const manager = lookups.permissions.includes("qc.view_all") && lookups.permissions.includes("qc.coaching_manage");
  const own = item.ownerId === lookups.currentUserId && lookups.permissions.includes("qc.actions_complete_own");
  async function save(path: string, body: unknown, method = "POST") { setBusy(true); setError(""); try { await apiFetch(path, { method, body: JSON.stringify(body) }); setEditing(false); setEvidence(""); setHistory(null); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Action failed."); } finally { setBusy(false); } }
  const transition = (action: string) => save(`/qc/actions/${item.id}/transition`, { version: item.version, action, evidence });
  return <article className="qc-card"><div className="qc-inline"><h2>{item.title}</h2><span className="qc-badge">{label(item.kind)} · {label(item.status)}</span>{item.dueAt && item.status !== "VERIFIED" && new Date(item.dueAt) < new Date() && <span className="qc-error">Overdue</span>}</div>
    <p className="qc-prewrap">{item.note}</p><p className="qc-muted">Owner: {personName(item.owner)} · Due {formatDate(item.dueAt)} · {(lookups.permissions.includes("qc.view_all") || item.review?.ownerId === lookups.currentUserId) ? <Link href={`/qc/reviews/${item.reviewId}`}>{item.review?.ticket?.ticketNumber ?? item.review?.deliverable?.name ?? "Open inspection"}</Link> : item.review?.ticket?.ticketNumber ?? item.review?.deliverable?.name ?? "Assigned follow-up"}</p>
    {(item.criterionId || item.finding) && <p>Linked finding: {item.finding ? label(item.finding.code) : item.review?.rubric?.criteria.find(criterion => criterion.id === item.criterionId)?.label ?? "Inspection rubric criterion"}</p>}
    {item.completionEvidence && <p className="qc-prewrap">Completion evidence: {item.completionEvidence}</p>}
    <p className="qc-muted">Acknowledged {formatDate(item.acknowledgedAt)} · Completed {formatDate(item.completedAt)} · Verified {formatDate(item.verifiedAt)}</p>
    {error && <p role="alert" className="qc-error">{error}</p>}
    <div className="qc-inline">{own && item.status === "OPEN" && <button disabled={busy} onClick={() => void transition("ACKNOWLEDGE")}>Acknowledge</button>}{own && item.status === "ACKNOWLEDGED" && <><label>Completion evidence<textarea value={evidence} onChange={event => setEvidence(event.target.value)} maxLength={5000} /></label><button disabled={busy || !evidence.trim()} onClick={() => void transition("COMPLETE")}>Submit completion</button></>}{manager && item.status === "COMPLETED" && <><button disabled={busy} onClick={() => void transition("VERIFY")}>Verify completion</button><label>Reason to return work<textarea value={evidence} onChange={event => setEvidence(event.target.value)} maxLength={5000} /></label><button disabled={busy || !evidence.trim()} onClick={() => void transition("RETURN")}>Return for correction</button></>}{manager && ["OPEN", "ACKNOWLEDGED"].includes(item.status) && <button disabled={busy} onClick={() => setEditing(!editing)}>Edit / reassign</button>}<button disabled={busy} onClick={() => { if (history) setHistory(null); else apiFetch<History[]>(`/qc/actions/${item.id}/history`).then(setHistory).catch(cause => setError(cause.message)); }}>{history ? "Hide history" : "View action history"}</button></div>
    {editing && <form className="qc-divider" onSubmit={event => { event.preventDefault(); const values = new FormData(event.currentTarget); const due = String(values.get("dueAt") ?? ""); void save(`/qc/actions/${item.id}`, { version: item.version, ownerId: values.get("ownerId"), title: values.get("title"), note: values.get("note"), dueAt: due ? new Date(due).toISOString() : null, reason: values.get("reason") }, "PATCH"); }}><div className="qc-form-grid"><label>Owner<select name="ownerId" defaultValue={item.ownerId}>{lookups.users.map(user => <option key={user.id} value={user.id}>{personName(user)}</option>)}</select></label><label>Due date<input name="dueAt" type="datetime-local" required={item.kind === "CORRECTIVE"} defaultValue={localInputDate(item.dueAt)} /></label><label>Title<input name="title" required maxLength={200} defaultValue={item.title} /></label></div><label>Feedback<textarea name="note" required maxLength={5000} defaultValue={item.note} /></label><label>Change reason<input name="reason" required maxLength={1000} /></label><p className="qc-muted">Reassignment requires the new owner to acknowledge the action. Previous activity remains in history.</p><button disabled={busy}>Save action changes</button><button type="button" onClick={() => setEditing(false)}>Cancel</button></form>}
    {history && <ol className="qc-action-history">{history.map(event => <li key={event.id}><strong>{label(event.action)}</strong> · {formatDate(event.createdAt)} · {personName(event.actor)}{["reason", "evidence", "note"].map(key => typeof event.metadata[key] === "string" ? <p className="qc-prewrap" key={key}>{String(event.metadata[key])}</p> : null)}{event.metadata.before && event.metadata.after ? <details><summary>Recorded changes</summary>{["ownerId", "title", "note", "dueAt"].map(key => { const before = (event.metadata.before as Record<string, string>)[key], after = (event.metadata.after as Record<string, string>)[key]; const display = (value: string) => key === "ownerId" ? personName(lookups.users.find(user => user.id === value)) : value || "Not set"; return before !== after ? <p key={key}>{label(key)}: {display(before)} → {display(after)}</p> : null; })}</details> : null}</li>)}</ol>}
  </article>;
}
