"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { apiFetch } from "@/lib/api";
import { Lookups, formatDate, label, personName } from "./qc.types";
interface Delivery { recipientId: string; attemptEvents: Array<{ id: string; attempt: number; outcome: string; createdAt: string }>; id: string; reviewId: string | null; recipient: { firstName: string; lastName: string }; channel: string; state: string; attempts: number; nextAttemptAt: string; acceptedAt: string | null; acknowledgedAt: string | null; errorCode: string | null; createdAt: string; }
export function QcDeliveries({ lookups }: { lookups: Lookups }) {
  const [page, setPage] = useState(1);
  const [rows, setRows] = useState<Delivery[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [selected, setSelected] = useState<Delivery | null>(null); const [reason, setReason] = useState("");
  const reload = useCallback(async () => { setRows(await apiFetch<Delivery[]>(`/qc/deliveries?page=${page}&pageSize=100`)); }, [page]);
  useEffect(() => { reload().catch(cause => setError(cause.message)); }, [reload]);
  async function retry() { if (!selected) return; setBusy(true); setError(""); try { await apiFetch(`/qc/deliveries/${selected.id}/retry`, { method: "POST", body: JSON.stringify({ reason }) }); setSelected(null); setReason(""); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Retry could not be queued."); } finally { setBusy(false); } }
  return <div className="qc-stack">{error && <div className="qc-notice qc-error" role="alert">{error}</div>}<article className="qc-card"><div className="qc-inline"><h2>Delivery audit</h2><button disabled={busy} onClick={() => void reload().catch(cause => setError(cause.message))}>Refresh delivery status</button></div><p className="qc-muted">Intended deliveries in your scope, 100 per page. Provider acceptance and human acknowledgment are recorded separately. Uncertain outcomes require reconciliation before retry.</p><div className="qc-table-scroll"><table><thead><tr><th>Recipient</th><th>Channel</th><th>State</th><th>Scheduled</th><th>Accepted</th><th>Acknowledged</th><th>Action</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{personName({ id: "", ...row.recipient })}</td><td>{label(row.channel)}</td><td>{label(row.state)}<small>{row.errorCode ? label(row.errorCode) : ""}</small><details><summary>{row.attempts} attempts</summary>{row.attemptEvents.map(event => <small key={event.id}>#{event.attempt} · {label(event.outcome)} · {formatDate(event.createdAt)}</small>)}</details></td><td>{formatDate(row.nextAttemptAt)}</td><td>{formatDate(row.acceptedAt)}</td><td>{formatDate(row.acknowledgedAt)}</td><td>{row.state === "ACCEPTED" && !row.acknowledgedAt && row.recipientId === lookups.currentUserId && <button disabled={busy} onClick={() => { setBusy(true); apiFetch(`/qc/deliveries/${row.id}/acknowledge`, { method: "POST", body: "{}" }).then(reload).catch(cause => setError(cause.message)).finally(() => setBusy(false)); }}>Acknowledge</button>}{row.reviewId && lookups.permissions.includes("qc.view_all") && <Link href={`/qc/reviews/${row.reviewId}`}>Inspection</Link>}{["FAILED", "UNKNOWN"].includes(row.state) && lookups.permissions.includes("qc.notifications_manage") && <button onClick={() => setSelected(row)}>Reconcile & retry</button>}</td></tr>)}</tbody></table></div>{!rows.length && <p>No deliveries on this page.</p>}<div className="qc-inline qc-pagination"><button disabled={page <= 1 || busy} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page}</span><button disabled={rows.length < 100 || busy} onClick={() => setPage(page + 1)}>Next</button></div></article>{selected && <form className="qc-card" onSubmit={event => { event.preventDefault(); void retry(); }}><h2>Reconcile delivery</h2>{selected.state === "UNKNOWN" && <p className="qc-notice">The provider may already have delivered this notification. Confirm its outcome before requesting another attempt.</p>}<label>Verified outcome or configuration correction<textarea required maxLength={1000} value={reason} onChange={event => setReason(event.target.value)} /></label><div className="qc-inline"><button disabled={busy || !reason.trim()}>Record reconciliation & queue retry</button><button type="button" disabled={busy} onClick={() => setSelected(null)}>Cancel</button></div></form>}</div>;
}
