"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { QcCriterionResult } from "@avidity/shared";
import { apiFetch, getApiBaseUrl } from "@/lib/api";
import { Lookups, Review, label, formatDate, personName } from "./qc.types";
import { QcCreativeAttachments, CreativeAttachment } from "./QcCreativeAttachments";
import { ActionCard } from "./QcWorkspace";
interface Evidence { serviceMeasurement?: { complete: boolean; reason: string | null; clocks: Array<{ kind: string; state: string; elapsedMinutes: number; targetMinutes: number; startedAt: string; stoppedAt: string | null }> } | null; page?: number; hasMore?: boolean; ticket?: { attachments?: Array<{ id: string; originalFilename: string; scanStatus: string }>; meetings?: Array<{ id: string; title: string; agenda: string | null; startAt: string; status: string }>; projectWorkItems?: Array<{ project: { id: string; name: string } }>; subject: string; qcProfile: { resolutionNote: string | null; category: { name: string } | null } | null; messages: Array<{ id: string; bodyText: string; direction: string; createdAt: string; authorUser: { id: string; firstName: string; lastName: string } | null }> }; events?: Array<{ id: string; kind: string; occurredAt: string }>; timeEntries?: Array<{ id: string; startedAt: string; minutes: number; description: string }>; messagesTruncated?: boolean; deliverable?: { attachments?: CreativeAttachment[]; name: string; status: string; dueAt: string; deliveredAt: string | null; history: Array<{ id: string; action: string; createdAt: string; metadata: { note?: string } }> }; }
export function QcInspection({ id, lookups }: { id: string; lookups: Lookups }) {
  const [review, setReview] = useState<Review | null>(null); const [evidence, setEvidence] = useState<Evidence | null>(null);
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [rubricId, setRubricId] = useState("");
  const [billingReason, setBillingReason] = useState("");
  const [results, setResults] = useState<Record<string, QcCriterionResult>>({}); const [reviewerId, setReviewerId] = useState("");
  const [overrideReasons, setOverrideReasons] = useState<Record<string, string>>({});
  const [actionKind, setActionKind] = useState("COACHING"); const [actionOwner, setActionOwner] = useState(""); const [title, setTitle] = useState(""); const [note, setNote] = useState(""); const [dueAt, setDueAt] = useState("");
  const can = (permission: string) => lookups.permissions.includes(permission);
  const load = useCallback(async () => { const [item, source] = await Promise.all([apiFetch<Review>(`/qc/reviews/${id}`), apiFetch<Evidence>(`/qc/reviews/${id}/evidence`)]); setReview(item); setEvidence(source); setReviewerId(item.reviewerId ?? ""); setActionOwner(item.ownerId ?? ""); if (item.rubric) { setRubricId(item.rubric.id); setResults(Object.fromEntries((item.results ?? []).map(result => [result.criterionId, result]))); } }, [id]);
  useEffect(() => { setBusy(true); load().catch(cause => setError(cause.message)).finally(() => setBusy(false)); }, [load]);
  async function mutate(path: string, body: unknown, method = "POST") { setBusy(true); setError(""); try { await apiFetch(`/qc/${path}`, { method, body: JSON.stringify(body) }); await load(); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "The inspection could not be updated."); return false; } finally { setBusy(false); } }
  async function moreEvidence() {
    setBusy(true); setError("");
    try { const next = await apiFetch<Evidence>(`/qc/reviews/${id}/evidence?page=${(evidence?.page ?? 1) + 1}`); setEvidence(previous => ({ ...next, ticket: next.ticket && previous?.ticket ? { ...next.ticket, messages: [...previous.ticket.messages, ...next.ticket.messages] } : next.ticket, events: [...(previous?.events ?? []), ...(next.events ?? [])] })); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Evidence could not be loaded."); } finally { setBusy(false); }
  }
  const rubric = lookups.rubrics.find(item => item.id === rubricId) ?? review?.rubric;
  const editable = review?.status === "IN_REVIEW" && review.reviewerId === lookups.currentUserId && can("qc.reviews_perform");
  return <div className="qc-stack" aria-busy={busy}>{error && <div role="alert" className="qc-notice qc-error">{error}</div>}{!review ? <p>Loading inspection…</p> : <>
    <article className="qc-card"><div className="qc-inline"><h2>{review.ticket?.ticketNumber ?? review.deliverable?.name}</h2><span className="qc-badge">{label(review.status)}</span>{review.score !== null && <strong>{review.score} / 100</strong>}</div><p>{review.ticket?.subject ?? review.deliverable?.project.name}</p><p className="qc-muted">Owner: {personName(review.owner)} · Reviewer: {personName(review.reviewer)} · Selected {formatDate(review.createdAt)}</p><p>{review.selectionReasons.map(label).join(" · ")}</p><div className="qc-inline">{review.ticket && can("tickets.view") && <Link href={`/tickets/${review.ticketId}`}>Open ticket</Link>}{review.deliverable && can("projects.view") && <Link href={`/projects?project=${review.deliverable.project.id}`}>Open project</Link>}{review.status === "PENDING" && can("qc.reviews_perform") && <button disabled={busy} onClick={() => void mutate(`reviews/${id}/transition`, { version: review.version, action: "START" })}>Claim & start review</button>}{["PASSED", "FAILED", "COACHING_ISSUED"].includes(review.status) && can("qc.reviews_perform") && <button disabled={busy} onClick={() => void mutate(`reviews/${id}/transition`, { version: review.version, action: "CLOSE" })}>Close verified review</button>}{review.finalizedAt && !review.acknowledgedAt && review.ownerId === lookups.currentUserId && <button disabled={busy} onClick={() => void mutate(`reviews/${id}/transition`, { version: review.version, action: "ACKNOWLEDGE" })}>Acknowledge review</button>}</div>{can("qc.reviews_assign") && ["PENDING", "IN_REVIEW"].includes(review.status) && <div className="qc-inline"><label>Assign reviewer<select value={reviewerId} onChange={event => setReviewerId(event.target.value)}><option value="">Select a reviewer</option>{(lookups.reviewers ?? lookups.users).map(user => <option key={user.id} value={user.id}>{personName(user)}</option>)}</select></label><button disabled={!reviewerId || busy} onClick={() => void mutate(`reviews/${id}/assignment`, { version: review.version, reviewerId }, "PATCH")}>Assign</button></div>}</article>
    {review.billingState === "HELD" && <article className="qc-card"><h2>Billing held</h2><p>Financial estimate reports containing this work are blocked until an authorized release. External invoicing systems must check QC eligibility before invoicing.</p>{can("qc.billing_release") && <div className="qc-inline"><label>Release justification<input maxLength={1000} value={billingReason} onChange={event => setBillingReason(event.target.value)} /></label><button disabled={busy || !billingReason.trim()} onClick={() => void mutate(`reviews/${id}/billing-release`, { version: review.version, reason: billingReason })}>Release billing hold</button></div>}</article>}
    {review.findings.length > 0 && <article className="qc-card"><h2>Flag evidence</h2>{review.findings.map(finding => <div className="qc-divider" key={finding.id}><h3>{label(finding.code)} <span className="qc-badge">{finding.severity}</span></h3><dl>{Object.entries(finding.evidence).filter(([, value]) => value === null || typeof value !== "object").map(([key, value]) => <div key={key}><dt>{key.replaceAll(/([A-Z])/g, " $1")}</dt><dd>{value === null ? "Unavailable" : String(value)}</dd></div>)}</dl>{finding.overriddenAt ? <p>Overridden {formatDate(finding.overriddenAt)}: {finding.overrideReason}</p> : can("qc.flags_override") && <div className="qc-inline"><label>Override reason<input maxLength={1000} value={overrideReasons[finding.id] ?? ""} onChange={event => setOverrideReasons({ ...overrideReasons, [finding.id]: event.target.value })} /></label><button disabled={busy || !overrideReasons[finding.id]?.trim()} onClick={() => void mutate(`findings/${finding.id}/override`, { reason: overrideReasons[finding.id] })}>Record override</button></div>}</div>)}</article>}
    <div className="qc-columns qc-inspection-columns"><article className="qc-card"><h2>Source evidence</h2>{evidence?.serviceMeasurement && <><h3>Measured service commitments</h3>{!evidence.serviceMeasurement.complete && <p className="qc-notice">{evidence.serviceMeasurement.reason}. These clocks are excluded from contractual compliance.</p>}{evidence.serviceMeasurement.clocks.map((clock, index) => <p key={index}>{label(clock.kind)}: {clock.elapsedMinutes.toLocaleString()} / {clock.targetMinutes.toLocaleString()} business minutes · {label(clock.state)}<small>Started {formatDate(clock.startedAt)} · {clock.stoppedAt ? `Stopped ${formatDate(clock.stoppedAt)}` : "Awaiting qualifying completion"}</small></p>)}</>}{evidence?.ticket && <><p><strong>Category:</strong> {evidence.ticket.qcProfile?.category?.name ?? "Not recorded"}</p><h3>Resolution</h3><p className="qc-prewrap">{evidence.ticket.qcProfile?.resolutionNote ?? "No structured resolution note recorded."}</p><h3>Conversation</h3>{evidence.ticket.messages.map(message => <details key={message.id}><summary>{formatDate(message.createdAt)} · {label(message.direction)} · {personName(message.authorUser)}</summary><p className="qc-prewrap">{message.bodyText}</p></details>)}{evidence.hasMore && <button disabled={busy} onClick={() => void moreEvidence()}>Load more conversation and timeline</button>}<h3>Private attachments</h3>{evidence.ticket.attachments?.map(file => <p key={file.id}>{["BLOCKED", "SUSPICIOUS"].includes(file.scanStatus) ? `${file.originalFilename} — blocked by scanning` : <a href={`${getApiBaseUrl()}/qc/reviews/${id}/attachments/${file.id}`}>{file.originalFilename}</a>}</p>)}<h3>Meetings</h3>{evidence.ticket.meetings?.map(meeting => <details key={meeting.id}><summary>{meeting.title} · {formatDate(meeting.startAt)} · {label(meeting.status)}</summary><p className="qc-prewrap">{meeting.agenda}</p></details>)}{evidence.ticket.projectWorkItems?.map(item => <p key={item.project.id}>Project: {can("projects.view") ? <Link href={`/projects?project=${item.project.id}`}>{item.project.name}</Link> : item.project.name}</p>)}<h3>Recorded labor</h3>{evidence.timeEntries?.map(entry => <p key={entry.id}>{formatDate(entry.startedAt)} · {entry.minutes} min — {entry.description}</p>)}{!evidence.timeEntries?.length && <p>No labor recorded.</p>}<details><summary>Captured timeline ({evidence.events?.length ?? 0})</summary>{evidence.events?.map(event => <p key={event.id}>{formatDate(event.occurredAt)} · {label(event.kind)}</p>)}</details></>}{evidence?.deliverable && <><p>{label(evidence.deliverable.status)} · Due {formatDate(evidence.deliverable.dueAt)}</p><QcCreativeAttachments attachments={evidence.deliverable.attachments} deliverableId={review.deliverableId!} reviewId={review.id} />{evidence.deliverable.history.map(event => <div key={event.id}><h3>{label(event.action)} · {formatDate(event.createdAt)}</h3><p className="qc-prewrap">{event.metadata.note}</p></div>)}</>}</article>
    <article className="qc-card"><h2>Inspection checklist</h2>{review.policy && <p className="qc-muted">SLA: {review.policy.name} · revision {review.policy.revision}</p>}<label>Published rubric<select value={rubricId} disabled={!editable || busy || Boolean(review.rubric)} onChange={event => { setRubricId(event.target.value); setResults({}); }}><option value="">Select a rubric</option>{lookups.rubrics.filter(item => item.kind === (review.ticket ? "SERVICE" : "CREATIVE")).map(item => <option key={item.id} value={item.id}>{item.name} · revision {item.revision}</option>)}</select></label>{rubric && <><p className="qc-muted">Pass threshold {rubric.passThreshold}% · critical failures cannot pass.</p>{rubric.criteria.map(criterion => <fieldset key={criterion.id} className="qc-divider" disabled={!editable || busy}><legend>{criterion.label} · weight {criterion.weight}{criterion.critical ? " · critical" : ""}</legend><label>Result<select value={results[criterion.id]?.outcome ?? ""} onChange={event => setResults({ ...results, [criterion.id]: { criterionId: criterion.id, comment: results[criterion.id]?.comment ?? "", outcome: event.target.value as QcCriterionResult["outcome"] } })}><option value="">Choose a result</option><option value="PASS">Pass</option><option value="FAIL">Fail</option>{criterion.allowNotApplicable && <option value="NA">Not applicable</option>}</select></label><label>Reviewer comment{results[criterion.id]?.outcome === "FAIL" ? " (required)" : ""}<textarea maxLength={5000} value={results[criterion.id]?.comment ?? ""} onChange={event => setResults({ ...results, [criterion.id]: { criterionId: criterion.id, outcome: results[criterion.id]?.outcome, comment: event.target.value } })} /></label></fieldset>)}{editable && <button className="qc-primary" disabled={busy || rubric.criteria.some(criterion => !results[criterion.id]?.outcome || results[criterion.id].outcome === "FAIL" && !results[criterion.id].comment.trim())} onClick={() => void mutate(`reviews/${id}/score`, { version: review.version, rubricId, results: rubric.criteria.map(criterion => results[criterion.id]) })}>Finalize inspection</button>}</>}{!editable && !review.finalizedAt && <p>Claim the review to score its checklist.</p>}</article></div>
    {review.finalizedAt && review.status !== "CLOSED" && can("qc.coaching_manage") && <form className="qc-card" onSubmit={event => { event.preventDefault(); void mutate("actions", { reviewId: id, ownerId: actionOwner, kind: actionKind, title, note, ...(dueAt ? { dueAt: new Date(dueAt).toISOString() } : {}) }).then(ok => { if (ok) { setTitle(""); setNote(""); } }); }}><h2>Add follow-up or recognition</h2><div className="qc-form-grid"><label>Type<select value={actionKind} onChange={event => setActionKind(event.target.value)}><option value="COACHING">Coaching</option><option value="CORRECTIVE">Corrective action</option><option value="RECOGNITION">Recognition</option></select></label><label>Owner<select required value={actionOwner} onChange={event => setActionOwner(event.target.value)}><option value="">Select owner</option>{lookups.users.map(user => <option key={user.id} value={user.id}>{personName(user)}</option>)}</select></label><label>Due date<input type="datetime-local" required={actionKind === "CORRECTIVE"} value={dueAt} onChange={event => setDueAt(event.target.value)} /></label><label>Title<input required maxLength={200} value={title} onChange={event => setTitle(event.target.value)} /></label></div><label>Feedback<textarea required maxLength={5000} value={note} onChange={event => setNote(event.target.value)} /></label><button disabled={busy}>Create follow-up</button></form>}
    {review.actions?.map(action => <ActionCard key={action.id} item={action} lookups={lookups} reload={load} />)}
    <article className="qc-card"><h2>Audit history</h2>{review.history?.map(event => <p key={event.id}>{formatDate(event.createdAt)} · {event.actor ? personName(event.actor) : "QC automation"} · {label(event.action)}{typeof event.metadata.followUpReviewId === "string" && <Link href={`/qc/reviews/${event.metadata.followUpReviewId}`}> · Open follow-up inspection</Link>}{typeof event.metadata.note === "string" && <span className="qc-prewrap"> — {event.metadata.note}</span>}</p>)}</article>
  </>}</div>;
}
