"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { apiFetch } from "@/lib/api";
import { QcCreativeAttachments, CreativeAttachment } from "./QcCreativeAttachments";
import { QcTicketEvidence } from "./QcTicketEvidence";
import { Lookups, Page, Named, Person, label, personName, formatDate } from "./qc.types";
interface Deliverable { attachments?: CreativeAttachment[]; history?: Array<{ id: string; action: string; createdAt: string; metadata: { note?: string; dueAt?: string } }>; timeEntries?: WorkTicket["timeEntries"]; id: string; name: string; kind: string; project: Named; owner: Person; status: string; dueAt: string; deliveredAt: string | null; version: number; }
interface WorkTicket { id: string; ticketNumber: string; subject: string; profile: { version: number; categoryId: string | null; resolutionNote: string | null } | null; timeEntries: Array<{ id: string; technicianId: string; startedAt: string; minutes: number; description: string }>; }
export function QcWork({ creative, lookups, initialProjectId, initialTicketId }: { creative: boolean; lookups: Lookups; initialProjectId?: string; initialTicketId?: string }) {
  const [items, setItems] = useState<Page<Deliverable> | null>(null); const [page, setPage] = useState(1); const [projectId, setProjectId] = useState(initialProjectId ?? ""); const [selected, setSelected] = useState<Deliverable | null>(null);
  const [search, setSearch] = useState(""); const [tickets, setTickets] = useState<Array<{ id: string; ticketNumber: string; subject: string }>>([]); const [ticket, setTicket] = useState<WorkTicket | null>(null); const [category, setCategory] = useState(""); const [resolution, setResolution] = useState("");
  const [options, setOptions] = useState<{ events: Array<{ id: string; trackingNumber: string; eventName: string }>; articles: Array<{ id: string; title: string }> }>({ events: [], articles: [] }); const [eventId, setEventId] = useState(""); const [articleId, setArticleId] = useState("");
  const [name, setName] = useState(""); const [kind, setKind] = useState(""); const [ownerId, setOwnerId] = useState(""); const [dueAt, setDueAt] = useState(""); const [note, setNote] = useState(""); const [action, setAction] = useState("");
  const [timeStart, setTimeStart] = useState(""); const [minutes, setMinutes] = useState(""); const [description, setDescription] = useState(""); const [correctionId, setCorrectionId] = useState("");
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [reason, setReason] = useState("");
  const can = (permission: string) => lookups.permissions.includes(permission);
  const load = useCallback(async () => { if (creative) setItems(await apiFetch<Page<Deliverable>>(`/qc/deliverables?page=${page}${projectId ? `&projectId=${encodeURIComponent(projectId)}` : ""}`)); }, [creative, page, projectId]);
  useEffect(() => { load().catch(cause => setError(cause.message)); }, [load]);
  useEffect(() => { setEventId(""); setArticleId(""); if (creative && (selected?.project.id || projectId)) apiFetch<typeof options>(`/qc/projects/${selected?.project.id || projectId}/evidence-options`).then(setOptions).catch(cause => setError(cause.message)); else setOptions({ events: [], articles: [] }); }, [creative, projectId, selected?.project.id]);
  async function loadTicket(id: string) { setBusy(true); setError(""); try { const item = await apiFetch<WorkTicket>(`/qc/tickets/${id}`); setTicket(item); setCategory(item.profile?.categoryId ?? ""); setResolution(item.profile?.resolutionNote ?? ""); setCorrectionId(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Ticket could not be loaded."); } finally { setBusy(false); } }
  useEffect(() => { if (initialTicketId && !creative) void loadTicket(initialTicketId); }, [initialTicketId, creative]);
  async function mutate(path: string, body: unknown, method = "POST") { setBusy(true); setError(""); setNotice(""); try { await apiFetch(`/qc/${path}`, { method, body: JSON.stringify(body) }); await load(); if (selected) setSelected(await apiFetch<Deliverable>(`/qc/deliverables/${selected.id}`)); if (ticket) await loadTicket(ticket.id); setNotice("Saved with audit history."); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Work could not be saved."); return false; } finally { setBusy(false); } }
  return <div className="qc-stack">{error && <p className="qc-notice qc-error" role="alert">{error}</p>}{notice && <p className="qc-notice" role="status">{notice}</p>}
    {creative ? <><article className="qc-card"><div className="qc-inline"><h2>Creative deliverables</h2><label>Project<select value={projectId} onChange={event => { setProjectId(event.target.value); setPage(1); setSelected(null); }}><option value="">All permitted projects</option>{lookups.projects.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><div className="qc-table-scroll"><table><thead><tr><th>Deliverable</th><th>Project</th><th>Owner</th><th>Stage</th><th>Committed date</th></tr></thead><tbody>{items?.items.map(item => <tr key={item.id}><td><button className="qc-link-button" onClick={() => { setBusy(true); apiFetch<Deliverable>(`/qc/deliverables/${item.id}`).then(setSelected).catch(cause => setError(cause.message)).finally(() => setBusy(false)); setAction(""); setNote(""); setCorrectionId(""); }}>{item.name}</button><small>{item.kind}</small></td><td>{can("projects.view") ? <Link href={`/projects?project=${item.project.id}`}>{item.project.name}</Link> : item.project.name}</td><td>{personName(item.owner)}</td><td>{label(item.status)}</td><td>{formatDate(item.dueAt)}</td></tr>)}</tbody></table></div>{!items?.items.length && <p>No creative deliverables match this scope.</p>}<div className="qc-inline qc-pagination"><button disabled={busy || page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>{items?.total ?? 0} deliverables · page {page}</span><button disabled={busy || !items || page * items.pageSize >= items.total} onClick={() => setPage(page + 1)}>Next</button></div></article>
    {can("qc.work_record") && <form className="qc-card" onSubmit={event => { event.preventDefault(); void mutate("deliverables", { projectId, ownerId, name, kind, ...(eventId ? { eventId } : {}), dueAt: new Date(dueAt).toISOString() }).then(ok => { if (ok) { setName(""); setKind(""); } }); }}><h2>Create a deliverable</h2><p className="qc-muted">Select its existing project above. Record proof, approval and delivery evidence as the work progresses.</p><div className="qc-form-grid"><label>Linked Event & Services request<select value={eventId} onChange={event => setEventId(event.target.value)}><option value="">Project deliverable without an event</option>{options.events.map(item => <option key={item.id} value={item.id}>{item.trackingNumber} · {item.eventName}</option>)}</select></label><label>Name<input required maxLength={200} value={name} onChange={event => setName(event.target.value)} /></label><label>Deliverable type<input required maxLength={100} value={kind} onChange={event => setKind(event.target.value)} /></label><label>Owner<select required value={ownerId} onChange={event => setOwnerId(event.target.value)}><option value="">Choose owner</option>{lookups.users.map(user => <option key={user.id} value={user.id}>{personName(user)}</option>)}</select></label><label>Committed date<input required type="datetime-local" value={dueAt} onChange={event => setDueAt(event.target.value)} /></label></div><button disabled={busy || !projectId}>Create deliverable</button></form>}
    {selected && <article className="qc-card"><div className="qc-inline"><h2>{selected.name}</h2><button onClick={() => setSelected(null)}>Close detail</button></div><p>{label(selected.status)} · Due {formatDate(selected.dueAt)}</p><details><summary>Proof, revision and commitment history</summary>{selected.history?.map(event => <p key={event.id}>{formatDate(event.createdAt)} · {label(event.action)} · {event.metadata.note ?? ""}{event.metadata.dueAt ? ` · Commitment ${formatDate(event.metadata.dueAt)}` : ""}</p>)}</details><QcCreativeAttachments key={selected.id} attachments={selected.attachments} deliverableId={selected.id} canUpload={can("qc.work_record")} onUpdated={async () => setSelected(await apiFetch<Deliverable>(`/qc/deliverables/${selected.id}`))} /><h3>Recorded labor</h3>{selected.timeEntries?.map(entry => <div key={entry.id}><p>{formatDate(entry.startedAt)} · {entry.minutes} min · {entry.description}</p>{entry.technicianId === lookups.currentUserId && can("qc.work_record") && <button onClick={() => { setCorrectionId(entry.id); setMinutes(String(entry.minutes)); setDescription(entry.description); }}>Correct this entry</button>}</div>)}{can("qc.work_record") && <form onSubmit={event => { event.preventDefault(); void mutate(`deliverables/${selected.id}`, { version: selected.version, action, note, ...(articleId ? { knowledgeArticleId: articleId } : {}), ...(action === "RESCHEDULE" ? { dueAt: new Date(dueAt).toISOString() } : {}) }, "PATCH").then(ok => { if (ok) setSelected(null); }); }}><label>Record next step<select required value={action} onChange={event => setAction(event.target.value)}><option value="">Choose step</option>{["DRAFT", "REVISION"].includes(selected.status) && <option value="PROOF_SENT">Record proof sent</option>}{selected.status === "PROOF_SENT" && <option value="APPROVED">Record proof approval</option>}{["PROOF_SENT", "APPROVED"].includes(selected.status) && <option value="REVISION">Record revision request</option>}{selected.status === "APPROVED" && <option value="DELIVER">Record final delivery</option>}{selected.status !== "DELIVERED" && <option value="RESCHEDULE">Change commitment with reason</option>}</select></label>{action === "RESCHEDULE" && <label>New commitment<input required type="datetime-local" value={dueAt} onChange={event => setDueAt(event.target.value)} /></label>}<label>Knowledge Base procedure (optional)<select value={articleId} onChange={event => setArticleId(event.target.value)}><option value="">No procedure reference</option>{options.articles.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Evidence / approval record<textarea required maxLength={5000} value={note} onChange={event => setNote(event.target.value)} /></label><button disabled={busy || !action}>Record step</button></form>}</article>}</> : <>
      <form className="qc-card" onSubmit={event => { event.preventDefault(); setBusy(true); setError(""); apiFetch<typeof tickets>(`/qc/tickets?ticketId=${encodeURIComponent(search)}`).then(setTickets).catch(cause => setError(cause.message)).finally(() => setBusy(false)); }}><h2>Ticket work records</h2><div className="qc-inline"><label>Ticket number or subject<input required value={search} onChange={event => setSearch(event.target.value)} maxLength={100} /></label><button disabled={busy}>Find ticket</button></div>{tickets.map(item => <div key={item.id}><button className="qc-link-button" type="button" onClick={() => void loadTicket(item.id)}>{item.ticketNumber} — {item.subject}</button></div>)}</form>
      {ticket && <article className="qc-card"><h2>{ticket.ticketNumber} · {ticket.subject}</h2>{can("qc.work_record") && <form onSubmit={event => { event.preventDefault(); void mutate(`tickets/${ticket.id}`, { version: ticket.profile?.version ?? 0, categoryId: category || null, resolutionNote: resolution }, "PATCH"); }}><label>Service category<select value={category} onChange={event => setCategory(event.target.value)}><option value="">Not categorized</option>{lookups.categories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Resolution evidence<textarea value={resolution} onChange={event => setResolution(event.target.value)} maxLength={10000} /></label><button disabled={busy}>Save QC work details</button></form>}<h3>Recorded time</h3>{ticket.timeEntries.map(entry => <div className="qc-divider" key={entry.id}><p>{formatDate(entry.startedAt)} · {entry.minutes} minutes · {entry.description}</p>{entry.technicianId === lookups.currentUserId && can("qc.work_record") && <button onClick={() => { setCorrectionId(entry.id); setMinutes(String(entry.minutes)); setDescription(entry.description); }}>Correct this entry</button>}</div>)}{!ticket.timeEntries.length && <p>No time entries recorded.</p>}{can("qc.reviews_assign") && can("qc.view_all") && <form onSubmit={event => { event.preventDefault(); void mutate("reviews", { ticketId: ticket.id, reason }); }}><label>Reason for manual QC review<input required maxLength={1000} value={reason} onChange={event => setReason(event.target.value)} /></label><button disabled={busy}>Request inspection</button></form>}</article>}
    </>}
    {!creative && ticket && <QcTicketEvidence ticketId={ticket.id} lookups={lookups} onUpdated={() => loadTicket(ticket.id)} />}
    {can("qc.work_record") && (creative ? selected : ticket) && <form className="qc-card" onSubmit={event => { event.preventDefault(); void mutate("time-entries", { ...(creative ? { deliverableId: selected!.id } : { ticketId: ticket!.id }), startedAt: new Date(timeStart).toISOString(), minutes: Number(minutes), description, ...(correctionId ? { correctionOfId: correctionId } : {}) }).then(ok => { if (ok) { setMinutes(""); setDescription(""); setCorrectionId(""); } }); }}><h2>{correctionId ? "Append a time correction" : "Record completed work"}</h2><p className="qc-muted">Entries belong to your identity. Corrections preserve the original record.</p><div className="qc-form-grid"><label>Work started<input required type="datetime-local" value={timeStart} onChange={event => setTimeStart(event.target.value)} /></label><label>Minutes<input required type="number" min={1} max={1440} value={minutes} onChange={event => setMinutes(event.target.value)} /></label></div><label>Work description<textarea required maxLength={5000} value={description} onChange={event => setDescription(event.target.value)} /></label><div className="qc-inline"><button disabled={busy}>Save time entry</button>{correctionId && <button type="button" onClick={() => setCorrectionId("")}>Cancel correction</button>}</div></form>}
  </div>;
}
