"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ClipboardCheck, RefreshCw, Settings, Download } from "lucide-react";
import { QC_REVIEW_STATES } from "@avidity/shared";
import { subscribeAccessRefresh } from "@/lib/access-refresh";
import { apiFetch } from "@/lib/api";
import { Lookups, Overview, Page, Review, Action, label, metric, personName, formatDate } from "./qc.types";
import { QcSettings } from "./QcSettings";
import { QcInspection } from "./QcInspection";
import { QcDeliveries } from "./QcDeliveries";
import { QcWork } from "./QcWork";
import { QcProgramStatus, QcReadiness } from "./QcProgramStatus";
import { QcTicketReviewContext } from "./QcTicketReviewContext";

export function QcWorkspace({ section, initialFilters = {} }: { section: string[]; initialFilters?: Record<string, string> }) {
  const view = section[0] ?? "overview";
  const [refreshVersion, setRefreshVersion] = useState(0);
  const [lookups, setLookups] = useState<Lookups | null>(null);
  const [programStatus, setProgramStatus] = useState<QcReadiness | null>(null);
  const [overview, setOverview] = useState<Overview | null>(null);
  const [reviews, setReviews] = useState<Page<Review> | null>(null);
  const [actions, setActions] = useState<Action[]>([]);
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [client, setClient] = useState(initialFilters.clientId ?? ""); const [owner, setOwner] = useState(""); const [status, setStatus] = useState("");
  const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<Record<string, number>>({}); const [reason, setReason] = useState("");
  const query = new URLSearchParams({ ...(initialFilters.ticketId ? { ticketId: initialFilters.ticketId } : {}), ...(initialFilters.projectId ? { projectId: initialFilters.projectId } : {}), page: String(page), ...(client ? { clientId: client } : {}), ...(owner ? { ownerId: owner } : {}), ...(status ? { status } : {}), ...(from ? { from: `${from}T00:00:00.000Z` } : {}), ...(to ? { to: `${to}T23:59:59.999Z` } : {}) }).toString();
  const reload = useCallback(async () => {
    setBusy(true); setError("");
    try {
      const lookup = await apiFetch<Lookups>("/qc/lookups"); setLookups(lookup); if (initialFilters.scope === "mine" && !owner) setOwner(lookup.currentUserId);
      setProgramStatus(await apiFetch<QcReadiness>("/qc/readiness"));
      if (["overview", "scorecards", "clients"].includes(view)) setOverview(await apiFetch<Overview>(`/qc/overview?${query}`));
      if (view === "reviews" && !section[1]) { setReviews(await apiFetch<Page<Review>>(`/qc/reviews?${query}`)); setSelected({}); }
      if (view === "actions") setActions(await apiFetch<Action[]>(`/qc/actions?page=${page}&pageSize=100`));
    } catch (cause) { setError(cause instanceof Error ? cause.message : "QC could not be loaded."); }
    finally { setBusy(false); }
  }, [view, section[1], query]);
  useEffect(() => { void reload(); }, [reload]);
  useEffect(() => {
    let mounted = true;
    const unsubscribe = subscribeAccessRefresh(() => {
      void apiFetch<{ user: { permissions: string[] } }>("/auth/me").then(({ user }) => {
        if (mounted) setLookups(current => current ? { ...current, permissions: user.permissions } : current);
      }).catch(() => {});
    });
    return () => { mounted = false; unsubscribe(); };
  }, []);
  const can = (permission: string) => lookups?.permissions.includes(permission) ?? false;
  async function bulk() {
    setBusy(true); setError("");
    try { await apiFetch("/qc/reviews/bulk", { method: "POST", body: JSON.stringify({ items: Object.entries(selected).map(([id, version]) => ({ id, version })), reason }) }); setReason(""); await reload(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Disposition failed."); } finally { setBusy(false); }
  }
  async function exportReport(safe: boolean) {
    setBusy(true); setError("");
    try {
      const report = await apiFetch<Record<string, unknown>>(`/qc/exports/${safe ? "client" : "internal"}?${query}`);
      const lines: string[][] = [];
      const flatten = (value: unknown, path: string) => { if (Array.isArray(value)) { value.forEach((item, index) => flatten(item, `${path} / ${index + 1}`)); return; } if (value !== null && typeof value === "object") Object.entries(value).forEach(([key, item]) => flatten(item, path ? `${path} / ${key}` : key)); else lines.push([path, value === null ? "Not measurable" : String(value)]); };
      flatten(report, "");
      const csv = [["Metric", "Value"], ...lines].map(row => row.map(value => `"${(/^[=+@\-\t\r]/.test(value) ? "'" : "") + value.replaceAll('"', '""')}"`).join(",")).join("\r\n");
      const url = URL.createObjectURL(new Blob(["\uFEFF", csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = safe ? "client-service-performance.csv" : "qc-internal-report.csv"; link.click(); URL.revokeObjectURL(url);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Export failed."); } finally { setBusy(false); }
  }
  return <section className="qc-workspace" aria-busy={busy}>
    <header className="qc-heading"><div><span className="qc-eyebrow">Service assurance</span><h1><ClipboardCheck size={25} /> Quality Control</h1><p>Inspect work, resolve exceptions and track service quality.</p></div><div className="qc-inline"><button onClick={() => { setRefreshVersion(value => value + 1); void reload(); }} disabled={busy}><RefreshCw size={16} /> Refresh</button>{can("qc.settings_manage") && <Link className="qc-button" href="/qc/settings"><Settings size={16} /> Settings</Link>}</div></header>
    <nav className="qc-tabs" aria-label="Quality Control"><Link aria-current={view === "overview" ? "page" : undefined} href="/qc">Overview</Link><Link aria-current={view === "reviews" ? "page" : undefined} href="/qc/reviews">Review queue</Link><Link aria-current={view === "actions" ? "page" : undefined} href="/qc/actions">Coaching & actions</Link><Link aria-current={view === "creative" ? "page" : undefined} href="/qc/creative">Creative work</Link><Link aria-current={view === "scorecards" ? "page" : undefined} href="/qc/scorecards">Scorecards</Link><Link aria-current={view === "deliveries" ? "page" : undefined} href="/qc/deliveries">Delivery audit</Link><Link aria-current={view === "work" ? "page" : undefined} href="/qc/work">Work records</Link></nav>
    {error && <div className="qc-notice qc-error" role="alert">{error}</div>}
    {!lookups && !error && <p role="status">Loading QC access and configuration…</p>}
    {lookups && <>
      {view !== "settings" && !section[1] && programStatus && <QcProgramStatus status={programStatus} permissions={lookups.permissions} />}
      {view === "reviews" && !section[1] && initialFilters.ticketId && <QcTicketReviewContext key={initialFilters.ticketId} ticketId={initialFilters.ticketId} permissions={lookups.permissions} onRequested={reload} />}
      {["overview", "scorecards", "clients", "reviews"].includes(view) && !section[1] && <div className="qc-filters"><label>Client<select value={client} onChange={event => { setClient(event.target.value); setPage(1); }}><option value="">All permitted clients</option>{lookups.clients.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Technician<select value={owner} onChange={event => { setOwner(event.target.value); setPage(1); }}><option value="">All permitted technicians</option>{lookups.users.map(item => <option key={item.id} value={item.id}>{personName(item)}</option>)}</select></label><label>From (UTC)<input type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label>Through (UTC)<input type="date" value={to} onChange={event => setTo(event.target.value)} /></label>{view === "reviews" && <label>Status<select value={status} onChange={event => { setStatus(event.target.value); setPage(1); }}><option value="">All states</option>{QC_REVIEW_STATES.map(value => <option key={value} value={value}>{label(value)}</option>)}</select></label>}</div>}
      {["overview", "scorecards", "clients"].includes(view) && overview && <>
        {overview.program.processingErrorCode && <div role="alert" className="qc-notice qc-error">QC processing is pending retry. Last successful pass: {formatDate(overview.program.lastProcessingAt)}. Source events remain retained.</div>}<div className="qc-metrics">{[["Awaiting inspection", overview.quality.pending], ["Average QC score", metric(overview.quality.averageScore)], ["SLA compliance", metric(overview.service.slaCompliancePercent, "%")], ["Overdue actions", overview.followUp.overdue]].map(([title, value]) => <article className="qc-card" key={String(title)}><span>{title}</span><strong>{value}</strong></article>)}</div>
        <div className="qc-columns"><article className="qc-card"><h2>Service performance</h2><dl><dt>First response</dt><dd>{metric(overview.service.averageFirstResponseBusinessMinutes, " business min")} · n={overview.service.firstResponseSample}</dd><dt>Resolution</dt><dd>{metric(overview.service.averageResolutionBusinessMinutes, " business min")} · n={overview.service.resolutionSample}</dd><dt>Measured work cycles</dt><dd>{overview.service.completeCycles} of {overview.service.cycles}</dd><dt>Incomplete evidence</dt><dd>{overview.service.incompleteCycles}</dd><dt>Breached obligations</dt><dd>{overview.service.breachedObligations} of {overview.service.evaluatedObligations} evaluated</dd></dl></article><article className="qc-card"><h2>Inspection & follow-up</h2><dl><dt>Completed inspections in this period</dt><dd>{overview.quality.completedInPeriod ?? 0} · {overview.quality.failedInPeriod ?? 0} failed</dd><dt>QC pass rate</dt><dd>{metric(overview.quality.passRatePercent, "%")}</dd><dt>Reopened work cycles</dt><dd>{metric(overview.rework?.reopenCyclePercent, "%")} · {overview.rework?.reopenedCycles ?? 0} recorded</dd><dt>Individually scored</dt><dd>{overview.quality.scored} of {overview.quality.selected} selected</dd><dt>Administrative clearances</dt><dd>{overview.quality.bulkCleared}</dd><dt>Flags recorded</dt><dd>{overview.quality.flags}</dd><dt>Open follow-up</dt><dd>{overview.followUp.open}</dd><dt>Subsequent closures awaiting reinspection</dt><dd>{overview.followUp.reinspectionRemaining ?? 0}</dd><dt>Recognition</dt><dd>{overview.followUp.recognition}</dd></dl></article><article className="qc-card"><h2>Creative delivery</h2><dl><dt>Delivered</dt><dd>{overview.creative.delivered} of {overview.creative.total}</dd><dt>On time against original commitment</dt><dd>{overview.creative.originalCommitmentOnTime ?? 0} of {overview.creative.originalCommitmentSample ?? 0} evidenced deliveries</dd><dt>On time against current commitment</dt><dd>{overview.creative.onTime} of {overview.creative.delivered} delivered</dd><dt>Overdue</dt><dd>{overview.creative.overdue}</dd><dt>Average revision rounds</dt><dd>{metric(overview.creative.averageRevisionRounds)}</dd></dl></article></div>
        {overview.service.historical.cycles > 0 && <article className="qc-card"><h2>Retained historical performance</h2><p className="qc-muted">{overview.service.historical.basis}. Historical ownership uses the retained source record.</p><div className="qc-columns"><p>First public response: {metric(overview.service.historical.averageFirstResponseElapsedMinutes, " elapsed min")} · n={overview.service.historical.firstResponseSample}</p><p>Resolution: {metric(overview.service.historical.averageResolutionElapsedMinutes, " elapsed min")} · n={overview.service.historical.resolutionSample}</p></div></article>}
        {view === "scorecards" && overview.technicians && <article className="qc-card"><h2>Technician cohorts</h2><div className="qc-table-scroll"><table><thead><tr><th>Technician</th><th>Work cycles</th><th>Inspected</th><th>Average score</th><th>Pass rate</th><th>SLA compliance</th></tr></thead><tbody>{overview.technicians.map(row => <tr key={row.ownerId}><td>{personName(lookups.users.find(person => person.id === row.ownerId))}</td><td>{row.cycles}</td><td>{row.inspected}</td><td>{metric(row.averageScore)}</td><td>{metric(row.passRatePercent, "%")}</td><td>{metric(row.slaCompliancePercent, "%")}</td></tr>)}</tbody></table></div></article>}
        <article className="qc-card"><h2>Daily cohorts</h2><p className="qc-muted">{overview.period.cohort}. Incomplete evidence is excluded from SLA compliance.</p><div className="qc-table-scroll"><table><thead><tr><th>Started (UTC)</th><th>Cycles</th><th>Measurable</th><th>First response (business min)</th><th>Compliance</th></tr></thead><tbody>{overview.trends.map(row => <tr key={row.day}><td>{row.day}</td><td>{row.cycles}</td><td>{row.completeCycles}</td><td>{metric(row.averageFirstResponseBusinessMinutes)}</td><td>{metric(row.slaCompliancePercent, "%")}</td></tr>)}</tbody></table></div>{!overview.trends.length && <p>No measured work exists for this scope and period.</p>}</article>
        <footer className="qc-inline"><span className="qc-muted">Updated {formatDate(overview.generatedAt)}{overview.pendingSourceEvents !== null ? ` · ${overview.pendingSourceEvents} source events pending` : ""}</span>{can("qc.export_internal") && <button onClick={() => void exportReport(false)} disabled={busy}><Download size={16} /> Internal report</button>}{can("qc.export_client") && can("qc.view_all") && <button disabled={!client || busy} onClick={() => void exportReport(true)}><Download size={16} /> Client-safe report</button>}</footer>
      </>}
      {view === "reviews" && !section[1] && reviews && <article className="qc-card"><h2>Review queue <span className="qc-muted">({reviews.total})</span></h2><div className="qc-table-scroll"><table><thead><tr>{can("qc.reviews_bulk") && <th>Select</th>}<th>Work</th><th>Owner / reviewer</th><th>Reasons</th><th>State</th><th>Score</th><th>Selected</th></tr></thead><tbody>{reviews.items.map(item => <tr key={item.id}>{can("qc.reviews_bulk") && <td><input type="checkbox" aria-label={`Select ${item.ticket?.ticketNumber ?? item.deliverable?.name}`} disabled={item.status !== "PENDING" || item.findings.length > 0 || item.selectionReasons.join() !== "SAMPLE"} checked={item.id in selected} onChange={event => setSelected(previous => { const next = { ...previous }; if (event.target.checked) next[item.id] = item.version; else delete next[item.id]; return next; })} /></td>}<td><Link href={`/qc/reviews/${item.id}`}>{item.ticket?.ticketNumber ?? item.deliverable?.name}</Link><small>{item.ticket?.subject ?? item.deliverable?.project.name}</small><small>{item.ticket?.client?.name}</small></td><td>{personName(item.owner)}<small>{personName(item.reviewer)}</small></td><td>{item.selectionReasons.map(label).join(" · ")}</td><td><span className="qc-badge">{label(item.status)}</span></td><td>{item.score ?? "—"}</td><td>{formatDate(item.createdAt)}</td></tr>)}</tbody></table></div>{!reviews.items.length && <div className="qc-empty-state"><p>No reviews match these filters.</p><p className="qc-muted">{initialFilters.ticketId ? "An inspection appears here when this ticket is selected by the configured rules or an authorized user requests one." : "Reviews are created by configured quality rules or by an authorized manual request. Adjust the filters to find existing inspections."}</p>{!initialFilters.ticketId && <Link href="/qc/work">Find a ticket and view its QC work records</Link>}</div>}<div className="qc-inline qc-pagination"><button disabled={page <= 1 || busy} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} · {reviews.total} records</span><button disabled={page * reviews.pageSize >= reviews.total || busy} onClick={() => setPage(page + 1)}>Next</button></div>{Object.keys(selected).length > 0 && <div className="qc-inline"><label>Disposition reason<input value={reason} onChange={event => setReason(event.target.value)} maxLength={1000} /></label><button disabled={!reason.trim() || busy} onClick={() => void bulk()}>Clear {Object.keys(selected).length} routine reviews</button></div>}</article>}
      {view === "reviews" && section[1] && <QcInspection key={refreshVersion} id={section[1]} lookups={lookups} />}
      {view === "actions" && <div className="qc-stack">{!actions.length && <article className="qc-card">No coaching or corrective actions in your scope.</article>}{actions.map(item => <ActionCard key={item.id} item={item} lookups={lookups} reload={reload} />)}<div className="qc-inline qc-pagination"><button disabled={page <= 1 || busy} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page}</span><button disabled={actions.length < 100 || busy} onClick={() => setPage(page + 1)}>Next</button></div></div>}
      {view === "deliveries" && <QcDeliveries key={refreshVersion} lookups={lookups} />}
      {view === "settings" && (can("qc.settings_manage") ? <QcSettings key={refreshVersion} permissions={lookups.permissions} /> : <div className="qc-notice"><strong>QC settings permission is required.</strong><p>Your current access can open QC but cannot configure the program. A QC administrator needs the configuration permission; editing rubrics and notifications also requires their respective permissions.</p><Link href="/profile">Review your inherited access in Profile</Link></div>)}
      {["creative", "work"].includes(view) && <QcWork key={`${view}:${refreshVersion}`} creative={view === "creative"} lookups={lookups} initialProjectId={initialFilters.projectId} initialTicketId={initialFilters.ticketId} />}
    </>}
  </section>;
}
export function ActionCard({ item, lookups, reload }: { item: Action; lookups: Lookups; reload: () => Promise<void> }) {
  const [evidence, setEvidence] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function transition(action: string) { setBusy(true); setError(""); try { await apiFetch(`/qc/actions/${item.id}/transition`, { method: "POST", body: JSON.stringify({ version: item.version, action, evidence }) }); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Action failed."); } finally { setBusy(false); } }
  return <article className="qc-card"><div className="qc-inline"><h2>{item.title}</h2><span className="qc-badge">{label(item.kind)} · {label(item.status)}</span></div><p className="qc-prewrap">{item.note}</p><p className="qc-muted">{personName(item.owner)} · Due {formatDate(item.dueAt)} · {(lookups.permissions.includes("qc.view_all") || item.review?.ownerId === lookups.currentUserId) ? <Link href={`/qc/reviews/${item.reviewId}`}>Open inspection</Link> : item.review?.ticket?.ticketNumber ?? item.review?.deliverable?.name ?? "Assigned follow-up"}</p>{item.completionEvidence && <p className="qc-prewrap">Completion evidence: {item.completionEvidence}</p>}{error && <p role="alert" className="qc-error">{error}</p>}<div className="qc-inline">{item.ownerId === lookups.currentUserId && lookups.permissions.includes("qc.actions_complete_own") && <>{item.status === "OPEN" && <button disabled={busy} onClick={() => void transition("ACKNOWLEDGE")}>Acknowledge</button>}{item.status === "ACKNOWLEDGED" && <><label>Completion evidence<textarea value={evidence} onChange={event => setEvidence(event.target.value)} maxLength={5000} /></label><button disabled={busy || !evidence.trim()} onClick={() => void transition("COMPLETE")}>Submit completion</button></>}</>}{item.status === "COMPLETED" && lookups.permissions.includes("qc.coaching_manage") && <button disabled={busy} onClick={() => void transition("VERIFY")}>Verify completion</button>}</div></article>;
}
